//go:build !no_mcp

package mcp

import (
	"fmt"
	"strings"

	"github.com/tokibase/tokibase/core"
	"github.com/tokibase/tokibase/kernel"
)

func ruleCell(r *string) string {
	switch ruleState(r) {
	case "locked":
		return "locked"
	case "public":
		return "PUBLIC"
	}
	e := strings.ReplaceAll(*r, "|", `\|`)
	if r := []rune(e); len(r) > 80 {
		e = string(r[:80]) + "…"
	}
	return "`" + e + "`"
}

// GenerateDocs renders AGENTS.md and llms.txt for the instance.
// System collections and `_agents` are left out.
func GenerateDocs(app core.App) (agentsMD, llmsTxt string, err error) {
	all, err := app.FindAllCollections()
	if err != nil {
		return "", "", err
	}
	cols := []*kernel.Collection{}
	for _, c := range all {
		if !c.System {
			cols = append(cols, c)
		}
	}
	p := getProviders()
	connect := "claude mcp add tokibase -e " + EnvAgentKey + "=<agent key> -- toki mcp serve --dir " + app.DataDir()

	var b strings.Builder
	b.WriteString("# AGENTS.md\n\nGenerated by `toki gen agents-md`. This is a TokiBase instance (PocketBase compatible API). Agents work through an MCP server with their own identity, rule enforcement and audit.\n\n")
	b.WriteString("## Connect\n\n1. A human creates an agent: `toki agent create <name> --role reader|writer|operator [--collections a,b] --dir " + app.DataDir() + "`\n")
	b.WriteString("2. Add the server to the agent client (Claude Code):\n\n```\n" + connect + "\n```\n\n")
	b.WriteString("Cursor: add to `.cursor/mcp.json` a server `tokibase` with `command: toki`, `args: [mcp, serve, --dir, " + app.DataDir() + "]`, `env: {" + EnvAgentKey + ": <agent key>}`.\n\n")
	b.WriteString("## Rules of engagement\n\n- Start with `schema.list` and `schema.describe`; read `toki://docs/rules`.\n- Every write needs a `reason`. Deletes and batches with deletes or more than 100 operations are two-step: first call returns a plan and a `confirm_token` (valid 5 minutes), second call with the same arguments executes.\n- Roles: reader (schema, reads), writer (+ create/update/delete/batch), operator (+ audit, backup, replica, deny, lockout, samples; bypasses rules).\n- Reader and writer agents are evaluated against collection rules as an agent: `@request.auth.kind = \"agent\"`, `@request.auth.id` is the agent id, `@request.auth.role` its role (a rule such as `@request.auth.id != \"\"` therefore also admits agents; use `@request.auth.kind = \"user\"` to exclude them). Sandbox agents run writes as dry runs that are rolled back.\n- Do not change rules or schema with these tools; propose changes for a human to apply as a migration.\n- Calls are rate limited per agent and audited.\n\n")
	b.WriteString("## Collections\n\n")
	if len(cols) == 0 {
		b.WriteString("_No user collections yet._\n\n")
	}
	for _, c := range cols {
		fmt.Fprintf(&b, "### %s (%s)\n\n", c.Name, c.Type)
		names := make([]string, 0, len(c.Fields))
		for _, f := range c.Fields {
			names = append(names, fmt.Sprintf("%s:%s", f.GetName(), f.Type()))
		}
		fmt.Fprintf(&b, "Fields: %s\n\n| list | view | create | update | delete |\n| --- | --- | --- | --- | --- |\n| %s | %s | %s | %s | %s |\n\n",
			strings.Join(names, ", "), ruleCell(c.ListRule), ruleCell(c.ViewRule), ruleCell(c.CreateRule), ruleCell(c.UpdateRule), ruleCell(c.DeleteRule))
	}
	b.WriteString("Rule legend: locked = superusers only, PUBLIC = everyone including guests.\n\n")
	b.WriteString("## Modules enabled\n\n")
	if len(p.Modules) == 0 {
		b.WriteString("_unknown_\n")
	}
	for _, m := range p.Modules {
		b.WriteString("- " + m + "\n")
	}
	b.WriteString("\n## MCP tools\n\n`schema.list`, `schema.describe`, `records.query`, `records.get`, `records.create`, `records.update`, `records.delete`, `records.batch`, `rule.lint`, `rule.explain`, and for operators `audit.tail`, `audit.verify`, `backup.verify`, `replica.status`, `deny.tail`, `lockout.list`.\n")
	agentsMD = b.String()

	var l strings.Builder
	l.WriteString("# TokiBase instance\n\n> PocketBase compatible backend. AI agents connect through MCP (`" + connect + "`). See AGENTS.md for the rules of engagement.\n\n## Collections\n\n")
	for _, c := range cols {
		fmt.Fprintf(&l, "- %s (%s): list=%s view=%s create=%s update=%s delete=%s\n", c.Name, c.Type,
			ruleState(c.ListRule), ruleState(c.ViewRule), ruleState(c.CreateRule), ruleState(c.UpdateRule), ruleState(c.DeleteRule))
	}
	l.WriteString("\n## Modules\n\n")
	for _, m := range p.Modules {
		l.WriteString("- " + m + "\n")
	}
	return agentsMD, l.String(), nil
}
