package cmd

import (
	"context"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
	"github.com/tokibase/tokibase/core"
	"github.com/tokibase/tokibase/modules/backupcheck"
)

// NewBackupCommand creates the `backup` command (create; list, verify and verify-all need modules/backupcheck).
func NewBackupCommand(app core.App) *cobra.Command {
	command := &cobra.Command{
		Use:   "backup",
		Short: "Create, list and verify backups",
	}
	command.AddCommand(backupCreateCommand(app))
	addBackupVerifyCommands(command, app)
	return command
}

func backupCreateCommand(app core.App) *cobra.Command {
	return &cobra.Command{
		Use:          "create [name]",
		Short:        "Create a new backup (the name is autogenerated if omitted)",
		SilenceUsage: true,
		Args:         cobra.MaximumNArgs(1),
		RunE: func(command *cobra.Command, args []string) error {
			name := ""
			if len(args) > 0 {
				name = args[0]
			}
			if err := app.CreateBackup(context.Background(), name); err != nil {
				return err
			}
			backupcheck.Wait() // let the automatic verification finish and log
			color.Green("Backup created.")
			return nil
		},
	}
}
